---
- name: "ced Apache installation using contener docker"
  hosts: prod
  
  pre_tasks:
    - name: "ced Installation des packages linux"
      package: name='{{ item }}' state=present
      when: ansible_distribution == "CentOS"
      loop:
        - epel-release
        - wget
        - git
	 	
    - name: "ced Download python package"
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py
		
    - name: "ced Installation package python"
      command: python2.7 /tmp/get-pip.py
	  
    - name: "ced install docker python"
      pip: name=docker-py
  
  tasks:
    - name: "ced copy du fichier website"
      template:
        src: index.html.j2
        dest: /home/admin/index.html
	 
    - name: "ced Create Apache container"
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
        volumes:
          - /home/admin/index.html:/usr/local/apache2/htdocs/index.html
