all:
  vars:
    ansible_user: admin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client1:
      ansible_host: 10.0.2.4
    client2:
      ansible_host: 10.0.2.5
  vars:
    ansible_password: admin
    env: production

